[package]
name = "craft"
version = "0.1.0"
edition = "2024"

[dependencies]
ocaml = {git = "https://github.com/zshipko/ocaml-rs"}

[build-dependencies]
ocaml-build = {git = "https://github.com/zshipko/ocaml-rs", features=["dune"]}
